server:
  port: 8082

spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: email-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.wangyu.kafka
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

email-service:
  kafka:
    user-registered-topic: user-registered
